### ISSUE TITLE
[UNSOLVED]arch linux system freeze after connecting wifi

### ISSUE THREAD

**Issue by tianheg** [tianheg/blog#147]
更有条理的阐述解决过程： https://bbs.archlinuxcn.org/viewtopic.php?pid=48329#p48329

系统卡顿出现情况：	

1. 使用无线网时
2. 使用无线网且打开 Google Chrome 浏览器时

已尝试：

一、（Unsolved）回退 Linux 内核

现在暂时不卡顿，解决办法： 设置 BIOS U 盘启动，插入制作好的 USB 启动盘，进入 U 盘中的 arch 系统，然后执行命令：

 ```sh
mount /dev/sdb2 /mnt
arch-root /mnt /bin/bash
cd /var/cache/pacman/pkg
ls -a | grep linux
pacman -U linux-5.13.9.arch1-1-x86_64.pkg.tar.zst
# linux kernel: 5.13.10 --> 5.13.9
```

依然出现卡顿，推测是无线网的缘故，需要安装驱动。（驱动已安装）

二、（Unsolved）编辑了 `/etc/default/grub`：

```conf
# GRUB_CMDLINE_LINUX_DEFAULT="elevator=noop loglevel=3 quiet"
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet mds=full,nosmt"
```

三、（Unsolved）安装 dkms rtl8821ce-dkms-git

```sh
sudo pacman -S dkms
yay-S rtl8821ce-dkms-git
```

四、（Unsolved）取消挂载 Chrome 缓存至 /tmp

<https://github.com/tianheg/til/blob/main/content/operating-system/arch-installation-guide.md#:~:text=%E5%B0%86%20Google%20Chrome%20%E7%9A%84%E7%BC%93%E5%AD%98%E6%8C%82%E8%BD%BD%E5%88%B0%20/tmp>

五、需注意：因笔记本内存足够，所以未分配 swap 空间

六、[ryzen-test](https://github.com/suaefar/ryzen-test)

Tools to reproduce randomly crashing processes under load on AMD Ryzen processors on Linux.

七、可能安装了多余的显卡驱动 https://t.me/archlinuxcn_group/2072178

https://luoxu-search.vercel.app/search?g=1031857103&q=xf86+video+intel+%E5%8D%B8%E8%BD%BD

八、从网络连接过程考虑

提出问题：

1. Arch Linux 中 KDE 桌面环境，是怎样连接无线网的？
2. 无线网经过的软件和硬件是什么？

根据问题确定解决方案：逐一排除，找到出问题的软件/硬件

```
nmcli
enp2s0: connected to Wired connection 1
        "Realtek RTL8111/8168/8411"
        ethernet (r8169), E4:E7:49:9E:C1:35, hw, mtu 1500
        ip4 default
        inet4 192.168.1.106/24
        route4 0.0.0.0/0
        route4 192.168.1.0/24
        inet6 fe80::9cd6:e0b9:df44:d842/64
        route6 fe80::/64

wlp3s0: unavailable
        "Realtek RTL8821CE"
        wifi (rtw_8821ce), A6:5C:67:F8:9F:F6, sw disabled, hw, mtu 1500

lo: unmanaged
        "lo"
        loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536

DNS configuration:
        servers: 8.8.4.4 8.8.8.8
        interface: enp2s0

## 已经连接无线网
nmcli
enp2s0: connected to Wired connection 1
        "Realtek RTL8111/8168/8411"
        ethernet (r8169), E4:E7:49:9E:C1:35, hw, mtu 1500
        ip4 default
        inet4 192.168.1.106/24
        route4 0.0.0.0/0
        route4 192.168.1.0/24
        inet6 fe80::9cd6:e0b9:df44:d842/64
        route6 fe80::/64

wlp3s0: connected to TP-LINK_6389
        "Realtek RTL8821CE"
        wifi (rtw_8821ce), 0C:96:E6:09:43:BD, hw, mtu 1500
        inet4 192.168.1.105/24
        route4 0.0.0.0/0
        route4 192.168.1.0/24
        inet6 fe80::1945:586d:4d95:a207/64
        route6 fe80::/64

ip address show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether e4:e7:49:9e:c1:35 brd ff:ff:ff:ff:ff:ff
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 0c:96:e6:09:43:bd brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.105/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 6899sec preferred_lft 6899sec
    inet6 fe80::1945:586d:4d95:a207/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

九、无线网卡驱动 rtw_8821ce 的问题

ref: <https://www.reddit.com/r/archlinux/comments/n0zoo5/driver_issue_rtw88_8821ce/>

ref:

1. <https://wiki.archlinux.org/title/downgrading_packages#Downgrading_the_kernel>
2. <https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html>
3. <https://askubuntu.com/a/1250060>
4. <https://www.linprofs.com/blog/how-to-patch-the-intel-mds-bug/>
5. <https://wiki.archlinux.org/title/Security>
6. [rtl8821ce](https://wiki.archlinux.org/title/Network_configuration/Wireless#rtl8821ce)
  rtl8821ce-dkms-git provides a kernel module for the Realtek 8821ce chipset found in the Asus X543UA.
  This requires DKMS, so make sure you have your proper kernel headers installed.
7. <https://www.google.com/search?q=arch+system+freeze+wifi+site:bbs.archlinux.org&newwindow=1&prmd=sniv>

**Comment by tianheg** [comment]
journalctl output

[journal.txt](https://github.com/tianheg/blog/files/7004647/journal.txt)

**Comment by tianheg** [comment]
According to @bnjw5jhyxn's suggestion https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-904873497, I added oneline code to `/etc/modprobe.d/blacklist.conf`, comment my original configuration:

```conf
#blacklist rtw88_8821ce
options rtw88_pci disable_aspm=1
```

Reboot.

Exec some orders:

```sh
$ lspci -k
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
        Subsystem: Hewlett-Packard Company Device 831a
        Kernel driver in use: rtw_8821ce
        Kernel modules: rtw88_8821ce, 8821ce

$ journalctl -b | grep ASPM
Aug 25 08:02:21 arch kernel: ACPI FADT declares the system doesn't support PCIe ASPM, so disable it
Aug 25 08:02:21 arch kernel: acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI EDR HPX-Type3]
Aug 25 08:02:21 arch kernel: acpi PNP0A08:00: FADT indicates ASPM is unsupported, using BIOS configuration
Aug 25 08:02:21 arch kernel: r8169 0000:02:00.0: can't disable ASPM; OS doesn't have ASPM control
```

Now pc did not freezed. This is a way to solve the driver problem, but I think it may be dangerous through @lwfinger's words https://github.com/tomaspinho/rtl8821ce/issues/142#issuecomment-904882968.

**Comment by tianheg** [comment]
Talks about `options rtw88_pci disable_aspm=1`

**Comment by lwfinger** [comment]
@tianheg: There is nothing dangerous about using this module option. The fact that it works indicates that your BIOS is buggy, but it has always been buggy. No new "danger" has been introduced. Complain to your computer vendor!

**Comment by tianheg** [comment]
understood that, thank you! @lwfinger
