### ISSUE TITLE
[Bug] https://yidajiabei.xyz/ 无法访问

### ISSUE THREAD

**Issue by ryan4yin** [tianheg/blog#353]
如题，发现只有 https://www.yidajiabei.xyz/ 才能正常访问，感觉不太符合预期，可以考虑加个重定向？

**Comment by tianheg** [comment]
现在再试试？

本来用的原生 Nginx，后来想试试 Docker，又加了 [nginx-proxy](https://hub.docker.com/r/nginxproxy/nginx-proxy)。还不很熟悉怎么设置。经过刚才的一番搜索，终于解决了这个问题。

**Comment by tianheg** [comment]
笔记 https://www.yidajiabei.xyz/posts/nginx-redirect/#configure-with-docker

**Comment by ryan4yin** [comment]
嗯嗯，正常了~
