### ISSUE TITLE
样式问题：home 页面的版权信息

### ISSUE THREAD

**Issue by CyrusYip** [tianheg/blog#385]
视口高度较低时（手机横屏），版权信息覆盖了其他内容。

![Screenshot_20241017_210238](https://github.com/user-attachments/assets/98da2fe1-0c3b-418b-919d-b6ada0d232d8)

**Comment by tianheg** [comment]
多谢反馈这些问题，我今晚修复一下

**Comment by tianheg** [comment]
我取了个巧，模仿国外的博主重新设计了首页，把关于页的内容也放到了首页了
