### ISSUE TITLE
Effie 产品特点记录

### ISSUE THREAD

**Issue by tianheg** [tianheg/blog#64]
官网：https://www.effie.co/

- 支持 1-6 级标题
- 支持加粗、斜体，有序和无序列表，分隔线
- 无序列表可以生成思维导图

**Comment by EffieNotes** [comment]
已经更新了好多期咯，大大啥时候跟上呀～

**Comment by tianheg** [comment]
@EffieNotes 早就不用了

**Comment by EffieNotes** [comment]
这样啊，好可惜呀，最近好像更新的挺频繁的～
