### ISSUE TITLE
Lex Fridman 的对话播客

### ISSUE THREAD

**Issue by tianheg** [tianheg/blog#98]
- [ ] [Cal Newport](https://www.youtube.com/watch?v=y3Umo_jd5AA)
	- What is deep work?
	- Focus
- [ ] [Sara Walker](https://www.youtube.com/watch?v=-tDQ74I3Ovs)
	- the origin of life
- [ ] [Donald Knuth](https://www.youtube.com/watch?v=EE1R8FYUJm0)

**Comment by Haleymiranda79** [comment]
What is this

**Comment by tianheg** [comment]
@Haleymiranda79 A person(Lex Fridman)'s podcast, he often talk with some great people, then he'll post the conversation to the Youtube. These two videos are my choice.
